### ISSUE TITLE
Cannot run ncurses for a problem opening a terminal

### ISSUE THREAD

**Issue by vgonisanz** [vgonisanz/nci#9]
Some users try to `make env-create && make run` and the have this error:

```
Error opening terminal: xterm-256color.
make: *** [Makefile:62: run] Error 1
```
It seems that ncurses cannot find the terminal info. Usually, just installing package `ncurses-term` generate the required info, but with conan and the 6.2 version the error still appear.

The first step to analyze the terminal info is to execute command `infocmp`. This will generate an output like:

```
#	Reconstructed via infocmp from file: /home/vgonisanz/.terminfo/x/xterm-256color
blah blah blah
``` 
In my computer, I have the info in my home folder, that is a default path to use it. But it seems that @ntamurejocolorado have not that folder on $HOME/.terminalinfo, so it is possible to define an environment variable with the path where infocmp find the info, in example, with the above output you can solve the problem in this way:

```
export TERMINFO=/home/vgonisanz/.terminfo
```

Users with that error usually have the info in `usr/share/terminfo`, so it is easy to solve doing this

```
export TERMINFO=/usr/share/terminfo
```

This solution is only valid for the current bash session (it is a local environment variable) but you can add it into `.bashrc` or `.zshrc` to avoid re-define every session.

If someone know another way to solve that error please comment it.

## References

- [terminfo](https://linux.die.net/man/5/terminfo)
- [term info detailed](https://tldp.org/HOWTO/Text-Terminal-HOWTO-16.html)
- [S.O long question with multiple approach](https://stackoverflow.com/questions/12345675/screen-cannot-find-terminfo-entry-for-xterm-256color)

**Comment by vgonisanz** [comment]
Please confirm that fix the problem @ntamurejocolorado , @IslameN

**Comment by ntamurejocolorado** [comment]
Ok, now it works.

**Comment by IslameN** [comment]
In my case `infocmp` outputs `/lib/terminfo/x/xterm-256color`. Doing `export TERMINFO=/lib/terminfo/x/xterm-256color` or `export TERMINFO=/usr/share/terminfo` does not solve the issues.

Did I not understand correctly?

**Comment by vgonisanz** [comment]
Please try `export TERMINFO=/lib/terminfo`, I wrote the path wrong, I have edited now.

**Comment by IslameN** [comment]
It is working!

**Comment by vgonisanz** [comment]
Adding more references: https://invisible-island.net/ncurses/ncurses.faq.html#other_versions

I'm going to add this info in the NCI documentation.

**Comment by vgonisanz** [comment]
Added info to troubleshooting to the wiki. It will be released in the next master merge in ths PR: https://github.com/vgonisanz/nci/pull/8
